src/app/components/elements/LoginModal.tsx, src/app/layout.tsx, src/contexts/AuthContext.tsx, src/contexts/LiffContext.tsx, src/lib/firebase.ts
対応issue: #14 
- LINEでログイン ボタンからLIFFフレームワークを使ったログインを実装
1. liffログイン
2. LIFFからリダイレクトされ、取得できるようになる accessToken をAPI側に送付
3. Firebase AuthのcustomTokenを受け取り、auth.signInWithCustomToken
.envに以下を追加
```NEXT_PUBLIC_LIFF_LOGIN_ENDPOINT =https://localhost:3000```
=> LIFFログインを実装

src/app/activities/[id]/page.tsx, src/components/features/activity/ActivityDetailsHeader.tsx, src/components/features/activity/ActivityNavigationButtons.tsx
Please refer to the gemini-code-assist comments below for detailed changes.
=> style: Fine-tune activity carousel and navigation buttons on `/activities/[id]`

graphql.schema.json, src/app/participations/[id]/hooks/useCancelReservation.ts, src/app/participations/[id]/page.tsx, src/app/reservation/confirm/hooks/useReservationAction.ts, src/app/reservation/confirm/page.tsx, src/app/search/result/components/SearchResultHeader.tsx, src/app/search/result/hooks/useSearchResults.ts, src/app/search/result/page.tsx, src/graphql/experience/reservation/mutation.ts, src/graphql/reward/ticket/mutation.ts, src/types/graphql.tsx, src/utils/errorMessage.ts
Moved search header configuration logic to a new `useSearchResultHeader` hook for improved modularity and separation of concerns. Adjusted `SearchResultPage` and `useSearchResults` to integrate the new hook, reducing redundancy and centralizing the header management logic.
=> Refactor search header logic into a custom hook

src/app/activities/[id]/components/ActivityDetailsContent.tsx, src/app/activities/[id]/components/ActivityDetailsFooter.tsx, src/app/activities/[id]/page.tsx, src/app/activities/data/presenter.ts, src/app/articles/components/Card.tsx, src/app/articles/data/presenter.ts, src/app/places/components/Card.tsx, src/app/places/data/presenter.ts, src/app/sign-up/components/SignUpForm.tsx, src/app/users/components/UserProfileEdit.tsx, src/app/users/components/UserProfileHeader.tsx
- 日程がない時にボトムバーのボタンを非活性化されない
- 案内人のユーザーを推したらユーザー詳細に遷移
- place cardでarticleのintroductionをカードに表示させる、今表示されていない
- ユーザーのbioが中央寄せになっているので、左寄せに
- トップページで画像登録されていなかったりあんま見栄え良くないやつが目立ってる
- 拠点一覧のリストで横幅崩れてる
- ユーザー名の登録は「本名でする」と認識しやすくする（スプシで照合できないらしく）
=> [0523] 細かな修正たち

src/graphql/experience/opportunity/fragment.ts, src/graphql/experience/opportunity/query.ts, src/types/graphql.tsx
https://github.com/Hopin-inc/civicship-portal/pull/157
で Oppotunity に紐づく articles を参照しているが、articles をクエリで記述していなかったため取れていなったので修正
API の方ではすでに参照できるようになっている
https://github.com/Hopin-inc/civicship-api/blob/1ab599e0564cb31c6e781e4c152a9f625d7bd56d/src/application/domain/experience/opportunity/controller/resolver.ts#L122-L124
before
after
=> fix: include articles on GqlGetOpportunityQuery

src/app/articles/data/presenter.ts, src/app/articles/hooks/useArticles.ts, src/graphql/content/article/query.ts, src/types/graphql.tsx
This pull request refactors the handling of author-related data by introducing consistent terminology and making structural changes to improve clarity and maintainability.
- Updated `hostedOpportunitiesByAuthors` logic to rely on `relatedUsers` for consistency.
- Renamed `authors` to `relatedUsers`, and vice versa, in GraphQL queries and types to align terminology across the codebase.
- Refactored author mapping to use the `relatedUsers` field as a temporary workaround, with notes on potential long-term solutions.
=> Refactor and standardize author-related fields and mappings

src/contexts/LiffContext.tsx
Integrated the LIFF Inspector Plugin to enhance debugging capabilities during LIFF initialization. Additionally, commented out the logic for redirecting to the initial path, simplifying the initialization flow.
=> TEST: Add LIFF Inspector Plugin and remove initial path redirect

src/app/admin/reservations/page.tsx
Simplified the query logic by removing an unnecessary filter condition (`participationStatus`). Added a `console.log` statement to debug and track `reservations` data for better traceability.
=> Remove redundant filter and add debug log.

src/app/places/components/map/PlaceCardsSheet.tsx, src/app/places/hooks/usePlaceCards.ts
1. マーカーをクリックしたら、意図しないカードが表示される
2. 拠点一覧に表示されない拠点がある
- 1. ユーザーの操作によらないカルーセルの選択を判別し、処理を出し分けるようにした
- 理由：PlaceCardsSheet.tsxのuseEffect内で、カルーセルの選択が変わるたびにonPlaceSelectが呼び出されていた。これにより、マーカーをクリックした後にカルーセルが更新され、その後カルーセルのselectイベントが発火して別のマーカーが選択されていた。
- 2. 50件までしか取得していなかったので、100件まで取得するようにした。
=> fix: マーカーのフォーカス挙動と一覧に表示されない拠点があるのを修正

pnpm-lock.yaml, src/app/reservation/select-date/components/TimeSlotList.tsx, src/app/sign-up/page.tsx, src/app/sign-up/phone-verification/PhoneVerificationForm.tsx, src/app/sign-up/phone-verification/page.tsx
This pull request includes several improvements:
1. **Redirection Improvements**:  
- Introduced fallback to `liff.state` for `nextParam` retrieval to handle cases where `next` query parameter is unavailable, ensuring seamless redirection across sign-up and phone verification flows.
2. **Registration Cutoff Logic**:  
- Added logic to disable slot selection after a calculated registration cutoff date (seven days from the current date).  
- Updated related visual and state behaviors and dependency versions.
3. **Simplified User Experience**:  
- Removed redundant toast notifications on the sign-up page when users are already logged in, directly redirecting them to provide a smoother flow.  
No breaking changes have been introduced with these updates.
=> Update redirection and registration logic

src/app/places/[id]/components/PlaceFeaturedArticle.tsx, src/app/places/[id]/page.tsx, src/app/places/data/presenter.ts
拠点に複数人の案内人の体験が掲載されている場合、意図しない順序で表示されていることがある
簡易的に順序を逆にすることで解決する
例）https://www.neo88.app/places/cmahru0gg001vs60nnkqrgugc
- オーナーの方のインタビューや体験が最初に表示されていない
- マップの画像で見た時もパッと分からない
根本対応ではないが、今後同じようなケースがあれば `REVERSE_ORDER_PLACE_IDS` に ID を追加すれば対応可能
=> fix: reversable place item order

src/app/activities/[id]/components/ActivityDetailsContent.tsx, src/app/activities/[id]/components/ActivityDetailsFooter.tsx, src/app/activities/[id]/page.tsx
- LINE を使わず予約をする場合の表記変更（予約できないと勘違いされないように）
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/5acf2a99-02c5-459e-8750-a2db6c7e4d4c) | ![image](https://github.com/user-attachments/assets/bb77bbb9-81d9-4703-9998-df22dc8d1ce2) |
- キャンセルについての注意書きを非表示にできるように（特定のケースで要望があり）
=> fix: label for external booking on activity detail

src/app/places/data/hardOrder.ts, src/app/places/data/presenter.ts
```
This pull request introduces the `pickPrimaryArticleByPlaceId` function. This functionality allows the selection of a primary article for specific places based on predefined mappings, enabling improved content prioritization and flexibility in article ordering.
- Added `pickPrimaryArticleByPlaceId` for custom article ordering by place ID.
```
=> Add support for primary article selection by place ID

src/app/reservation/complete/page.tsx
This pull request updates the `phoneNumber` prop logic to utilize the phone number of the opportunity's creator instead of the reservation's creator. This ensures the displayed contact information is accurate and relevant.
=> Update phoneNumber prop to use opportunity creator info

next.config.mjs, src/lib/logging/client/utils.ts
- Refactored the server logging utilities' import path to match the correct file structure and ensure proper module resolution.
- Removed the `optimizeCss` setting from the configuration, which previously caused an error with the `critters` module.
=> Update logging imports and remove problematic CSS setting

src/app/admin/members/page.tsx
Increase the pagination limit for member list fetching to display more members per page load, improving admin efficiency.
=> feat(admin): increase member list fetch limit from 100 to 200

src/app/reservation/complete/components/CompletionHeader.tsx, src/app/reservation/complete/page.tsx
- CompletionHeaderコンポーネントに承認要否のプロパティを追加し、表示内容を動的に変更。
- 予約完了時のメッセージを条件に応じて更新するロジックを実装。
=> 主催者の承認不要（requiredApproval.false）の場合にも、申込完了画面で主催者からの承認必要な旨を表示している

src/app/reservation/confirm/components/NotesSection.tsx, src/app/reservation/confirm/page.tsx, src/components/shared/NoticeCard.tsx
close #504 
予約確認ページにNoticeCardコンポーネントを追加し、申し込み未確定の注意メッセージを表示する機能を実装しました。
- NoticeCardコンポーネントを新規作成
- 予約確認ページに注意メッセージを表示する機能を追加
- 「申し込みを確定」というボタンの名前ではなく、「申し込みをする」に変更（確定は承認後なので誤解を招く可能性がある）
- 注意書きの欄に未ログイン時には、ログインする必要があることを追記
- src/components/shared/NoticeCard.tsx (新規作成)
- その他関連ファイルの更新
=> 予約確認ページにNoticeCardコンポーネントを追加し、申し込み未確定の注意メッセージを表示する機能を実装

graphql.schema.json, src/app/activities/components/CarouselSection/CarouselSection.tsx, src/app/activities/data/presenter.ts, src/app/components/CardHorizontal.tsx, src/app/participations/[id]/components/OpportunityInfo.tsx, src/app/participations/[id]/page.tsx, src/app/quests/components/QuestsList.tsx, src/app/reservation/complete/components/ReservationDetails.tsx, src/app/reservation/complete/page.tsx, src/app/reservation/confirm/components/ExpectedPoints.tsx, src/app/reservation/confirm/components/OpportunityInfo.tsx, src/app/reservation/confirm/components/PaymentSection.tsx, src/app/reservation/confirm/components/PaymentSummary.tsx, src/app/reservation/confirm/components/payment/PointsToggle.tsx, src/app/reservation/confirm/components/payment/TicketsToggle.tsx, src/app/reservation/confirm/hooks/useReservationAction.ts, src/app/reservation/confirm/page.tsx, src/app/search/result/components/SearchResultHeader.tsx, src/app/tickets/hooks/useAvailableTickets.ts, src/graphql/experience/reservation/fragment.ts, src/types/graphql.tsx, src/utils/date.ts, src/utils/index.ts
> 関連タスク
- [予約完了画面でポイント、またはチケットを使用時に現地でも支払い額が正しく反映されていない](https://github.com/Hopin-inc/civicship-portal/issues/507)
- [/participations/[id] のデザイン修正](https://github.com/Hopin-inc/civicship-portal/issues/511)
- [参加人数を3人で予約して、2人だけポイント利用しても問題ないかとか見ておく](https://github.com/Hopin-inc/civicship-portal/issues/509)
- [予約完了・確認画面のデザイン修正](https://github.com/Hopin-inc/civicship-portal/issues/512)
- 日付が長い際に見出しが潰れている。同じ年の際は日付のみで良い
> 画面収録
- 日付が長い際に見出しが潰れている。同じ年の際は日付のみで良い
- 予約完了画面でポイント、またはチケットを使用時に現地でも支払い額が正しく反映されていない
- 参加人数を3人で予約して、2人だけポイント利用しても問題ないかとか見ておく
https://github.com/user-attachments/assets/b2a012f5-0eaa-4fc0-9c6f-1c120650a079
- /participations/[id] のデザイン修正
=> ポイント、チケット関連の実装・デザイン修正

src/app/reservation/confirm/page.tsx
close #504 
| 未ログイン状態 | ログイン状態 |
|--------|--------|
| <img width="468" height="500" alt="image" src="https://github.com/user-attachments/assets/ad75265e-b9f3-4b7a-bf24-7ebb75bcc62a" /> | <img width="455" height="428" alt="image" src="https://github.com/user-attachments/assets/301a15b4-9704-49cd-9411-526daf41ef9f" /> |
=> fix: 予約画面のボタンラベルをわかりやすいように変更

src/app/admin/reservations/hooks/useGetReservationStatusMeta.ts
```
Refactor cancellation status checks to differentiate between reservation and slot cancellations.
This change improves code clarity when handling different types of cancellations, ensuring more accurate status handling.
```
=> Refactor cancellation status checks for clarity.

src/app/components/CardHorizontal.tsx, src/app/participations/[id]/components/OpportunityInfo.tsx, src/app/participations/[id]/page.tsx, src/app/quests/[id]/page.tsx, src/app/reservation/complete/components/ReservationDetails.tsx, src/app/reservation/complete/page.tsx, src/app/reservation/confirm/components/OpportunityInfo.tsx, src/app/reservation/confirm/components/PaymentSection.tsx, src/app/reservation/confirm/components/PaymentSummary.tsx, src/app/reservation/confirm/page.tsx, src/utils/date.ts
> タスク内容
- 問題：チケット利用してないなら「チケット利用分」は不要
- PRで解決したこと : チケットを使用していない場合は表示しないように修正
- 画面収録 : https://4hopin.slack.com/archives/C0945JVF2DP/p1753767811389519
- 問題：日時は「日付」「時間帯」で区切って2行表示が良い
- PRで解決したこと : 日時、時間帯を区切って二行で表示するように実装、
- 既存のdisplayDurationの関数にフラグを追加して2行にするかしないかを選択できるように実装
- 画面収録 : https://4hopin.slack.com/archives/C0945JVF2DP/p1753767951861949
- 問題 : 料金内訳のところに、謎の0が表示されている
- PRで解決したこと : 条件分岐を修正して条件に満たない場合はnullを返すようにし0が表示されないように実装
- 画面収録 : https://4hopin.slack.com/archives/C0945JVF2DP/p1753770710402659
- 問題 : 体験詳細画面へ遷移できない
- PRで解決したこと : 再利用できるように作成したコンポーネントにLinkをつけれていなかったため追加して遷移できるように実装
- 画面収録 : https://4hopin.slack.com/archives/C0945JVF2DP/p1753770755868519
- 問題 : 詳細画面へ遷移した際にログが出たままになっている
- PRで解決したこと : 不要なconsole.logを削除
- 問題 : participationsのデザインは、reservationsのデザインを当てた方が良い
- 補足 : …
=> 予約確認画面のUI改善とナビゲーション修正

src/app/sign-up/components/SignUpForm.tsx
close #575 
以下の理由で、何も入力せず登録できてしまっていた
- Zodのz.string()は、文字列型であることを検証しますが、空文字列（""）も有効な文字列として扱います
-  required_errorは、フィールドがundefinedやnullの場合にのみ発動し、空文字列には適用されません
- フォームのデフォルト値がname: ""（空文字列）に設定されていたため、フィールドは技術的には「存在」していた
- フォームのデフォルト値を undefined した
- trim をした上で validation を挟んで、スペースや空文字だけでも登録できないようにした
- name のフォームバリデーショんエラーがあったら、アカウントを作成のボタンを disabled にした
=> fix: ユーザーの名前を必ず登録されるように修正

src/app/activities/components/ActivitiesList.tsx, src/app/quests/components/QuestsList.tsx, src/app/search/result/hooks/useSearchResults.ts
- LoadingIndicatorコンポーネントをインポートし、無限スクロールのローディング状態を表示する要素を追加
- useSearchResultsフックに無限スクロールのロジックを実装し、データの取得を最適化
- 各リストコンポーネントでローディング状態を管理し、ユーザー体験を向上
動画はテストのため一件ずつ取得するようにしていますので若干挙動変かもです
実際にローカルで試していただけますと嬉しいです。
https://github.com/user-attachments/assets/831b6e36-376a-4404-a0b1-df17be91b5b2
=> ActivitiesListとQuestsListに無限スクロール用のローディングインジケーターを追加

src/config/activityBookingConfig.ts
CloudRun の値は更新済みなので、このまま問題なければマージ可能
予約受け入れ日数を前日・2日前まで受付られるようにするものを2つ追加した
背景：https://github.com/Hopin-inc/civicship-portal/pull/559
こちらの関係でフロントのみ環境変数ではなく、ハードコードで対応している
=> chore: update ACTIVITY_BOOKING_CONFIG 予約受付日数のカスタム設定

docs/development/liff-auth-config.md, src/app/layout.tsx, src/config/auth-config.ts, src/contexts/AuthProvider.tsx, src/hooks/auth/useAutoLogin.ts, src/hooks/auth/useLiffInitialization.ts
- 環境変数を使用して認証パスをカスタマイズ可能に
- `AuthProvider`コンポーネントでの認証設定の適用
- 自動ログインおよびLIFF初期化フックでの条件チェックを追加
=> - 認証が必要なページのパスを`src/config/auth-config.ts`に定義
