Hopin-inc/civicship-portal

src/app/activities/[id]/components/ActivityDetailsContent.tsx, src/app/activities/[id]/components/ActivityDetailsHeader.tsx, src/types/graphql.tsx
Please refer to the gemini-code-assist comments below for detailed changes.
=> fix(ui): refine activity ActivityDetailsHeader style

src/app/activities/[id]/components/ActivityDetailsContent.tsx, src/app/activities/[id]/components/ActivityDetailsFooter.tsx, src/app/activities/[id]/components/ActivityScheduleCard.tsx, src/app/activities/[id]/components/SimilarActivitiesList.tsx, src/app/articles/components/Card.tsx
Please refer to the gemini-code-assist comments below for detailed changes.
=> fix(ui): refine activity bottom components

src/app/users/[id]/page.tsx, src/app/users/components/UserProfileHeader.tsx, src/app/users/components/UserProfileSection.tsx, src/app/users/me/page.tsx
=> Refine my page style(top)

src/app/users/components/UserProfileEdit.tsx, src/app/users/hooks/useProfileEdit.ts, src/app/users/me/edit/page.tsx, src/components/ui/label.tsx
=> refine edit profile page

src/app/activities/[id]/components/ActivityDetailsHeader.tsx, src/app/articles/components/Card.tsx, src/app/places/[id]/components/PlaceAddress.tsx, src/app/places/[id]/components/PlaceFeaturedArticle.tsx, src/app/places/[id]/components/PlaceOpportunities.tsx, src/app/places/[id]/components/PlaceOverview.tsx, src/app/places/[id]/hooks/usePlaceDetail.ts, src/app/places/[id]/page.tsx, src/components/ui/images-carousel.tsx
=> Refine place detail page

src/app/places/components/Card.tsx, src/app/places/components/map/CustomMarker.tsx, src/app/places/components/map/PlaceCardsSheet.tsx
=> Refine map list style

src/app/activities/[id]/page.tsx, src/app/articles/[id]/page.tsx, src/app/participations/[id]/hooks/useParticipationPage.ts, src/app/participations/[id]/page.tsx, src/app/places/[id]/page.tsx, src/app/reservation/complete/page.tsx, src/app/reservation/confirm/components/NotesSection.tsx, src/app/reservation/select-date/page.tsx, src/app/search/result/page.tsx, src/app/users/[id]/page.tsx, src/app/wallets/[id]/page.tsx, src/components/shared/ErrorState.tsx
This pull request includes the following updates:
- Refactored routing to use `useParams` and `useSearchParams` hooks, replacing props-based parameter passing for cleaner and more consistent route handling.
- Enhanced null/undefined safety checks and removed unused code and type definitions.
- Updated the layout and button styles for the `ErrorState` component, ensuring typography, spacing, and button sizes align with the design system guidelines.
=> Refactor routing and improve ErrorState UI consistency

src/app/users/components/UserPortfolioList.tsx
=> feat: user page

src/app/articles/components/Card.tsx, src/app/reservation/complete/components/CompletionHeader.tsx, src/app/reservation/complete/components/ReservationDetails.tsx, src/app/reservation/complete/page.tsx, src/app/reservation/confirm/components/NotesSection.tsx, src/app/reservation/confirm/components/OpportunityInfo.tsx, src/app/reservation/confirm/components/ParticipationAge.tsx, src/app/reservation/confirm/components/PaymentSection.tsx, src/app/reservation/confirm/components/ReservationDetailsCard.tsx, src/app/reservation/confirm/page.tsx, src/app/reservation/select-date/components/SelectionSheet.tsx, src/app/reservation/select-date/page.tsx
=> Refine reservation flow / pages style

src/app/participations/[id]/components/ParticipationActions.tsx, src/app/participations/[id]/components/ParticipationStatusNotification.tsx, src/app/participations/[id]/page.tsx, src/components/ui/button.tsx
=> Refine reservation detail page styles

src/app/activities/components/Card/CardVertical.tsx, src/app/activities/components/CarouselSection/CarouselSection.tsx, src/app/activities/components/ListSection/ListSection.tsx
=> fix: activities layout

src/app/admin/reservations/[id]/page.tsx
- Refactored the reservation details page by reorganizing imports, standardizing spacing, and correcting formatting inconsistencies. These adjustments enhance code readability and maintainability without affecting functionality.
- Updated the filter key from `cityCodes` to `stateCodes` to align with the updated naming convention, ensuring consistency and reducing potential mismatches in location-based filters.
=> Refactor reservation details and update filter key naming

src/hooks/useHierarchicalNavigation.ts
- navigation の戻るの挙動を修正した
- 必ずしも、上の階層に戻る訳ではないので、history から back させるようにした
=> Fix: back navigation behavior

src/app/activities/[id]/components/SimilarActivitiesList.tsx, src/app/places/[id]/components/PlaceOpportunities.tsx, src/app/users/components/UserPortfolioList.tsx
=> feat(ui): add carousel style to activity cards in horizontal lists

src/app/search/components/SearchBox.tsx
=> fix(ui): improve SearchBox component styling

graphql.schema.json, src/app/admin/reservations/[id]/page.tsx, src/app/reservation/confirm/components/ParticipationAge.tsx, src/app/reservation/confirm/hooks/useReservationAction.ts, src/app/reservation/confirm/hooks/useReservationUIState.ts, src/app/reservation/confirm/page.tsx, src/graphql/experience/reservation/fragment.ts, src/types/graphql.tsx
```
This pull request includes the following updates:
1. **Refactor Reservation Page**:
- Added stricter types and null checks for reservation and opportunity fields.
- Implemented fallback mechanisms for missing opportunity data, such as default images and text.
- Enhanced code robustness to prevent runtime issues and improve user experience.
2. **Support for Reservation Comments**:
- Introduced a new "comment" field in the Reservation object to allow additional details to be included.
- Updated the UI and GraphQL layer to handle and render the `comment` field.
3. **Add Participant Age Comments**:
- Added support to capture and store participant age-related comments in reservations.
- Updated the `ParticipationAge` component and associated hooks for input handling.
- Enhanced the schema …
```
=> Refactor reservation page and add support for reservation comments

src/app/activities/data/presenter.ts, src/app/participations/[id]/data/presenter.ts, src/app/reservation/data/presenter/reservation.ts
Updated presenter logic to pass and handle article references consistently across reservations, participations, and activities. Improved the clarity of fallback logic for interviews within the activity presenter.
=> Refactor article handling in presenter functions

package.json, pnpm-lock.yaml, src/app/activities/[id]/components/ActivityDetailsContent.tsx, src/app/activities/[id]/components/ActivityDetailsFooter.tsx, src/app/activities/[id]/components/ActivityScheduleCard.tsx, src/app/activities/[id]/page.tsx, src/app/activities/data/presenter.ts, src/app/activities/data/type.ts, src/app/activities/page.tsx, src/app/admin/members/page.tsx, src/app/admin/reservations/[id]/page.tsx, src/app/participations/[id]/components/ParticipationActions.tsx, src/app/participations/[id]/data/presenter.ts, src/app/participations/[id]/layout.tsx, src/app/participations/[id]/page.tsx, src/app/reservation/data/presenter/opportunitySlot.ts, src/app/reservation/data/type/opportunitySlot.ts, src/app/reservation/select-date/components/TimeSlotList.tsx, src/app/reservation/select-date/hooks/useReservationDateHandler.ts, src/components/layout/Header.tsx, src/components/ui/dialog.tsx, src/contexts/AuthContext.tsx, src/contexts/HeaderContext.tsx, src/graphql/experience/opportunity/query.ts, src/graphql/experience/opportunitySlot/query.ts, src/types/graphql.tsx
- Refactored activity components with reservation cutoff logic (7 days prior to the event).
- Introduced the `isReservable` flag to determine slot availability.
- Updated related presenter logic to include the `isReservable` field and handle slot availability more effectively.
- Simplified the `GetOpportunitySlots` GraphQL query, added reusable fragments, and extended type definitions for reservations and participations.
- Enhanced reservation UI elements to reflect new cutoff logic and slot availability.
- Adjusted sorting order for opportunities to display the earliest available ones first.
- Improved user-facing UI/UX, including better error handling during LIFF login, additional dialog confirmations, and clearer button labels.
=> Update activity reservation logic and UI enhancements

src/app/activities/[id]/layout.tsx, src/app/activities/layout.tsx, src/app/activities/metadata.ts, src/app/articles/[id]/layout.tsx, src/app/articles/metadata.ts, src/app/layout.tsx, src/app/login/layout.tsx, src/app/login/metadata.ts, src/app/places/[id]/layout.tsx, src/app/places/layout.tsx, src/app/places/metadata.ts, src/app/privacy/layout.tsx, src/app/privacy/metadata.ts, src/app/sign-up/layout.tsx, src/app/sign-up/metadata.ts, src/app/terms/layout.tsx, src/app/terms/metadata.ts, src/app/tickets/layout.tsx, src/app/tickets/metadata.ts, src/app/users/[id]/layout.tsx, src/app/wallets/layout.tsx, src/app/wallets/metadata.ts
This pull request introduces significant updates to enhance SEO, social sharing, and layout organization across various pages of the application. Below are the changes included:
- Added metadata and layout components for the following pages:
- Activities
- Login
- Signup
- Privacy Policy
- Terms
- Tickets
- Wallets
- Places
- Enhanced metadata generation for individual articles and pages by dynamically configuring Open Graph and Twitter details.
- Implemented a global metadata file to provide consistent defaults for articles and sections.
- Replaced default description fallback for user bio with an empty string to ensure accurate metadata.
- Specified canonical URLs and refined viewport configurations to improve SEO and maintainability.
These updates aim to provide better sharing …
=> Add layout and metadata enhancements for pages

src/app/admin/components/AdminGuard.tsx, src/app/admin/layout.tsx, src/app/admin/metadata.ts, src/app/admin/slots/[id]/page.tsx, src/app/participations/[id]/layout.tsx, src/app/places/[id]/layout.tsx, src/app/reservation/complete/layout.tsx, src/app/reservation/complete/metadata.ts, src/app/reservation/confirm/layout.tsx, src/app/reservation/confirm/metadata.ts, src/app/reservation/select-date/layout.tsx, src/app/reservation/select-date/metadata.ts, src/app/search/layout.tsx, src/app/search/metadata.ts, src/app/search/result/layout.tsx, src/app/search/result/metadata.ts, src/app/users/me/layout.tsx, src/app/users/me/metadata.ts, src/hooks/useOpportunitySlots.ts, src/hooks/useSlotParticipations.ts
```markdown
This pull request includes significant updates and improvements to metadata and layout components across various pages. The changes encompass:
- **Modular metadata enhancements**:
- Consolidated metadata logic with dedicated files for better SEO and Open Graph configuration.
- Added dynamic metadata generation capabilities for pages like places, articles, and activities.
- **Layout refactoring**:
- Introduced specific layout components for pages such as login, sign-up, and Privacy Policy.
- Enhanced layout structure with reusable components like `AdminGuard` for scalability and readability.
- **Query and type safety improvements**:
- Updated GraphQL queries to align with the new metadata generation logic.
- Strengthened type safety by switching to generated GraphQL hooks and …
```
=> Refactor metadata and layout components for scalability

src/app/admin/reservations/hooks/useReservations.ts
Reverts Hopin-inc/civicship-portal#177
=> Revert "Fix infinite loading in admin/reservations page"

src/app/admin/components/AdminGuard.tsx, src/app/sign-up/page.tsx, src/app/sign-up/phone-verification/PhoneVerificationForm.tsx, src/app/sign-up/phone-verification/line-browser/page.tsx, src/app/sign-up/phone-verification/page.tsx, src/contexts/AuthContext.tsx
---
This pull request contains multiple improvements to the phone verification flow and related pages. It enhances user redirection logic, refines the handling of authentication states, and adds a loading indicator for better clarity and user experience.
1. **Refactored Sign-Up Page**:
- Added client-side authentication logic with `useAuth` and `useRouter`.
- Redirects logged-in users to their profile.
- Displays a loading indicator during authentication.
2. **PhoneVerificationForm Enhancements**:
- Introduced a loading state to handle asynchronous actions.
- Updated import paths to use absolute paths.
- Removed unused variables and refined dependencies.
3. **Phone Verification Improvements**:
- Added a dedicated page for unsupported LINE browsers, including user instructions and actions. …
=> Refactor phone verification flow for improved user experience

src/contexts/AuthContext.tsx
Removed redundant retry logic and adjusted user data fetching to reduce complexity. Replaced `loading` with more descriptive `authLoading` and `gqlLoading` states. Added additional console logs for better debugging and ensured proper state updates after authentication flow.
=> Refactor auth data fetching and simplify loading logic

src/app/admin/components/AdminGuard.tsx, src/app/page.tsx, src/components/layout/Header.tsx, src/contexts/AuthContext.tsx, src/contexts/LiffContext.tsx, src/hooks/useInitialLiffRedirect.ts
```
- Refactored `AdminGuard` logic to improve user validation processes and enhance readability.
- Simplified homepage redirection by removing redundant checks and directly routing to "/activities."
- Updated Header logo link destination to point to the homepage, enhancing user navigation experience.
- Introduced a `useInitialLiffRedirect` hook to manage and streamline LIFF path redirection logic.
- Cleaned up console logs and standardized code formatting for maintainability.
These changes collectively improve code clarity, user navigation flow, and maintainability.
```
=> Refactor navigation and authentication logic for clarity

src/contexts/LiffContext.tsx
Reverts Hopin-inc/civicship-portal#186
=> Revert "TEST: Add LIFF Inspector Plugin and remove initial path redirect"

src/app/admin/reservations/page.tsx, src/app/reservation/complete/page.tsx, src/app/reservation/confirm/hooks/useReservationAction.ts, src/app/reservation/confirm/hooks/useReservationUIState.ts, src/app/reservation/confirm/page.tsx, src/graphql/experience/reservation/mutation.ts, src/types/graphql.tsx
- Enhanced the reservation flow to integrate participant count into various components and hooks, ensuring accurate display and management.
- Extended the GraphQL schema to incorporate participation details including source, status, reason, images, and description.
- Updated mutations to support the new participation data model.
=> Update reservation and GraphQL schema for participant details

graphql.schema.json, src/app/admin/reservations/[id]/page.tsx, src/app/admin/reservations/hooks/cancellation/useCancelSlot.ts, src/types/graphql.tsx
```
This pull request adds an optional comment field to the opportunity slot cancellation flow. This allows users to provide additional context when cancelling a reservation. The GraphQL schema, types, and cancellation hook have been updated to support this change. The reservations page has also been modified to include the comment functionality.
- Introduced a comment field to the cancellation process.
- Updated GraphQL schema and types to handle the new field.
- Enhanced cancellation hook to process comments.
- Modified reservations page to include and display the comment input functionality.
```
=> Add comment field to cancellation flow

src/app/places/components/Card.tsx
=> fix(ui): place list layout

src/app/activities/[id]/components/ActivityDetailsContent.tsx, src/app/places/[id]/components/PlaceAddress.tsx, src/app/places/hooks/usePlacesData.ts, src/components/shared/AddressMap.tsx, src/utils/maps/geocoding.ts
住所検索からだと位置がずれてしまう、拠点は既に設定されている緯度経度から算出するようにした
=> fix: prioritize existing lat/lng for specific locations on map display

src/app/places/data/presenter.ts, src/graphql/location/place/query.ts
- Added reverse order ID handling for improved display positioning.
- Updated GraphQL queries to include nested `place` fields.
- Renamed `authors` field to `relatedUsers` for better clarity and consistency.
- Refactored LIFF (LINE Front-end Framework) authentication and sign-up flows for a smoother user onboarding experience.
=> Refactor GraphQL queries and enhance authentication flows

src/app/places/components/map/CustomMarker.tsx
This pull request introduces a mapping of hardcoded coordinates for specific marker IDs. It updates the marker position logic to prioritize these hardcoded coordinates whenever they are available, ensuring consistent placement for predefined markers. If no hardcoded data exists for a marker ID, the fallback logic utilizes dynamic data to
=> Use hardcoded coordinates for specific markers

package.json, pnpm-lock.yaml, src/lib/logging/client/index.ts, src/lib/logging/client/utils.ts, src/lib/logging/server/index.ts, src/lib/logging/server/route.ts, src/lib/logging/server/utils.ts, src/lib/logging/type.ts
Introduce logging interfaces and utilities for server environments, including ID generation, masking, and operation tracking. Implement a server-side API to handle client log submissions and enrich logs with metadata. Update dependencies to include required logging and tracing packages.
=> Add server logging utilities and integrate with API routes

src/app/places/components/map/CustomMarker.tsx, src/utils/maps/geocoding.ts
Replaced an outdated hardcoded place ID with the correct one for "大庄屋" in multiple files. Added a debug log in `CustomMarker` to verify hardcoded coordinates during initialization.
=> Update hardcoded coordinates and add logging for markers

src/app/places/components/map/CustomMarker.tsx, src/app/places/data/hardOrder.ts, src/app/places/data/presenter.ts, src/utils/maps/geocoding.ts
Refactored opportunity ordering logic by introducing reusable utilities (`getPrimaryOpportunity`, `orderOpportunities`) and centralizing control in `hardOrder.ts`. Updated hardcoded marker coordinates, improving consistency for specific marker IDs, and added debug logging in `CustomMarker` for initialization verification.
=> Refactor opportunity ordering and update marker coordinates

src/app/activities/data/presenter.ts, src/app/places/data/presenter.ts
```markdown
This pull request includes the following changes:
1. **Fee Fallback Improvements:**
- Replaced logical OR (`||`) with nullish coalescing (`??`) for `feeRequired` property. This ensures accurate fallback behavior for explicitly set falsy values (`false`, `0`).
2. **Article Handling Refactor in Place Presenter:**
- Switched from user-based article selection to opportunity-based article mapping for headline and bio fields. Improves clarity and data consistency by removing user-authored references.
3. **ActivityDetails Component Updates:**
- Isolated `ActivityBodySection` from `ActivityDetailsContent`.
- Simplified `NoticeSection` logic, removed unused props and constants.
- Introduced `linkify-it` dependency for better text rendering with links.
```
=> Refactor data handling and update ActivityDetails components

src/app/activities/data/presenter.ts, src/app/places/data/presenter.ts
Reverts Hopin-inc/civicship-portal#252
=> Revert "Refactor data handling and update ActivityDetails components"

src/app/places/data/hardOrder.ts
=> fix: add nakagawablueberry to OPPORTUNITY_ORDER_BY_PLACE

src/app/activities/[id]/components/ActivityDetailsContent.tsx, src/app/activities/data/presenter.ts, src/app/participations/[id]/data/presenter.ts, src/app/reservation/confirm/components/NotesSection.tsx, src/app/reservation/data/presenter/opportunitySlot.ts, src/app/reservation/select-date/components/TimeSlotList.tsx, src/utils/errorMessage.ts
開催日時の1週間前をきったら、予約できない制限を前日（24時間前）まで予約できるようにした
=> fix: reservation limit 7days ago -> 1days ago

src/app/admin/reservations/components/AttendanceSheet.tsx
- Updated the AttendanceSheet component to skip rendering participation cards when no user data is linked, ensuring a cleaner UI and reducing errors.
- Increased wallet data query fetch limit to 500 for improved performance.
- Addressed deployment configuration in GitHub workflow for proper production environment setup.
=> Fix issues with AttendanceSheet and improve wallet query limit

src/app/admin/reservations/hooks/useGetReservationStatusMeta.ts
This pull request introduces several major changes and improvements:
1. **Refactor Reservation Logic**: Updated status logic by replacing `participating` with `participated` for improved clarity and simplified conditionals for evaluating reservation statuses.
2. **GraphQL Enhancements**: Added CRUD operations for articles and extended city queries with pagination. Updated the thumbnail type for articles to improve data handling.
3. **Reservation Query Update**: Included user details (id and name) in reservation queries to enhance contextual data availability.
=> Refactor reservation logic and enhance application features

graphql.schema.json, src/app/admin/credentials/components/opportunity/OpportunityList.tsx, src/app/admin/credentials/components/selectDate/TimeSlotSelector.tsx, src/app/admin/credentials/components/selectUser/CredentialRecipientSelector.tsx, src/app/admin/credentials/components/selectUser/SearchForm.tsx, src/app/admin/credentials/hooks/useMemberWithDidSearch.ts, src/app/admin/members/hooks/useMembershipQueries.ts, src/app/admin/wallet/grant/components/HistoryTab.tsx, src/app/admin/wallet/grant/components/MemberTab.tsx, src/app/admin/wallet/grant/components/SearchSection.tsx, src/app/admin/wallet/grant/data/presenter/transaction.ts, src/app/admin/wallet/grant/hooks/useWalletsAndDidIssuanceRequests.ts, src/app/admin/wallet/grant/page.tsx, src/graphql/account/membership/query.ts, src/graphql/account/wallet/query.ts, src/graphql/transaction/query.ts, src/types/graphql.tsx
> 下記2点の修正
- フロントでのDID発行状態が正しく表示されない
- 同一ユーザーが重複表示される
=> 検索フォームにEnterキーでの検索機能を追加し、メンバー検索のクエリにcommunityIdを追加。トランザクション表示のロジックを改善し、コードの可読性を向上。

src/app/admin/wallet/grant/hooks/useWalletsAndDidIssuanceRequests.ts
```
This pull request updates the fetch policy in the `useWalletsAndDidIssuanceRequests` hook from `"cache-and-network"` to `"network-only"`. The change ensures that data is fetched directly from the server to prioritize real-time accuracy over possible cache inconsistencies.
```
=> Update fetch policy to network-only in wallet data hook

src/app/wallets/donate/page.tsx
- `useGetMemberWalletsQuery`の変数に`withDidIssuanceRequests`を追加し、DID発行リクエストを取得できるように修正
https://github.com/user-attachments/assets/b6bdb2c8-28ef-47da-ae24-eff50de43b65
=> GraphQLクエリにDID発行リクエストを含めるオプションを追加

src/app/admin/credentials/[id]/components/StatusCard.tsx, src/app/admin/credentials/[id]/page.tsx, src/app/admin/credentials/components/CreateOpportunity.tsx, src/app/admin/credentials/components/CredentialIssuanceWizard.tsx, src/app/admin/credentials/components/opportunity/OpportunityList.tsx, src/app/admin/credentials/components/selectDate/TimeSlotSelector.tsx, src/app/admin/credentials/components/selectUser/CredentialRecipientSelector.tsx, src/app/admin/credentials/components/selectUser/Member.tsx, src/app/admin/credentials/components/selectUser/SearchForm.tsx, src/app/credentials/[id]/components/CredentialList.tsx, src/components/layout/MainContent.tsx
- 主催者や概要、開始日時、終了日時のラベルのスタイルを変更し、テキストサイズを調整
- DIDの表示部分を条件付きでレンダリングするように修正
- StatusCardコンポーネントのスタイルを改善
- MemberコンポーネントではDIDのトランケートサイズを変更し、SearchFormコンポーネントのスタイルを簡素化しました。
- ステップ管理のロジックを改善し、URLパラメータを使用してウィザードの進行状況を追跡可能に修正。
- CreateOpportunityコンポーネントの遷移先を更新し、各ステップでの遷移を明確にしました。
https://github.com/user-attachments/assets/ce69eb75-60dc-4794-9a1a-6e98ec4ccbcb
https://github.com/user-attachments/assets/97b98117-c18c-471e-8ea3-4dbee4350b31
=> credentialsページをデザイン通りに修正

graphql.schema.json, src/app/admin/credentials/hooks/useMemberWithDidSearch.ts, src/app/admin/wallet/grant/components/MemberTab.tsx, src/app/admin/wallet/grant/components/TransferInputStep.tsx, src/app/admin/wallet/grant/components/UserSelectStep.tsx, src/app/admin/wallet/grant/page.tsx, src/app/admin/wallet/page.tsx, src/app/tickets/hooks/useTicketClaimLinks.ts, src/app/wallets/components/WalletCard.tsx, src/app/wallets/data/presenter.ts, src/app/wallets/data/type.ts, src/app/wallets/donate/page.tsx, src/graphql/reward/ticketClaimLink/query.ts, src/types/graphql.tsx
---
This pull request refactors the wallet logic to use BigInt for the `currentPoint` field, ensuring better handling of large numbers. Key changes include updating the types, components, and related logic to ensure consistency and prevent potential data inaccuracies. Furthermore, various components and hooks were adjusted to enhance readability, type accuracy, and maintainability.
- Replaced `number` with `BigInt` for `currentPoint` across the wallet logic and related components.
- Refactored `useMemberWithDidSearch` to incorporate the new `BigInt` handling and simplify the code structure.
- Adjusted `updateQuery` formatting within `useTicketClaimLinks` for better readability and consistency.
- Introduced the `TicketClaimLinks` GraphQL query and associated hooks, along with updated …
=> Refactor wallet logic to use BigInt for currentPoint

src/app/activities/[id]/components/ActivityScheduleCard.tsx, src/app/reservation/complete/components/ReservationDetails.tsx, src/app/reservation/confirm/components/ReservationDetailsCard.tsx, src/app/reservation/select-date/components/TimeSlotList.tsx, src/utils/date.ts
Reverts Hopin-inc/civicship-portal#439
=> Revert "日を跨ぐ開催枠の表記が同日仕様になっている"

src/app/admin/credentials/components/opportunity/OpportunityList.tsx, src/app/admin/credentials/components/selectDate/TimeSlotSelector.tsx, src/app/admin/credentials/components/selectUser/CredentialRecipientSelector.tsx
Implemented a consistent loading state behavior by introducing a unified `LoadingIndicator` component. Applied this component to `CredentialRecipientSelector`, `OpportunityList`, and `TimeSlotSelector` for improved user experience.
=> Add unified loading states across components

src/app/login/components/LoginModal.tsx, src/app/reservation/confirm/page.tsx, src/app/tickets/receive/page.tsx
=> hotfix: LIFFでの予約画面からアカウント登録に進もうとすると、画面が切り替わらない

graphql.schema.json, src/app/activities/[id]/components/ActivityDetailsContent.tsx, src/app/activities/[id]/components/ActivityDetailsHeader.tsx, src/app/activities/[id]/hooks/useOpportunityDetail.ts, src/app/activities/data/presenter.ts, src/app/articles/data/presenter.ts, src/graphql/experience/opportunity/query.ts, src/middleware.ts, src/types/graphql.tsx
Adjust numerous UI and logic components:
- Default thumbnail set to an empty string instead of null.
- Replaced the Image component with Avatar, including null checks.
- Hid location details when place name or address is missing.
- Updated `slotFilter` to support an array for `hostingStatus`.
- Refactored opportunity presenter logic with added `opportunityId` for `ActivitySlot`.
- Enhanced GraphQL types with `CommunityConfig` and `OpportunitySlotCreate`.
Also includes merged middleware updates allowing access to `activities/[id]` for communities without the opportunities feature, tested for relevant cases.
=> Update UI components and refine opportunity detail handling

src/app/components/PageClient.tsx, src/app/data/fetchActivities.ts, src/hooks/useFeatureCheck.ts, src/lib/communities/metadata.ts
https://github.com/user-attachments/assets/f3f4cc40-2636-484e-8e49-80960862bdca
=> metadataのfeatureフラグにquestsが入っていない場合に非表示するように実装

src/app/components/CardHorizontal.tsx, src/app/components/CardVertical.tsx, src/app/reservation/confirm/components/OpportunityInfo.tsx
> 含まれてるタスク
- 問題 : pointsRequireを0にすると、潰れたラベルがカードの左上に表示されている
- PRで解決したこと : pointsRequireが0の場合もBadgeを表示しないように条件を追加しました
- 問題 : 主催者の電話番号のフォントは黒字太字ではない
- PRで解決したこと : figmaのデザイン通りに文字サイズ・行間を修正
- 画面収録 : https://4hopin.slack.com/archives/C0945JVF2DP/p1753775320344869
- 問題 : 予約確認、完了画面でopportunityのタイトルのフォントサイズが違う
- PRで解決したこと : figma通りにフォントサイズを修正
- 画面収録 : https://4hopin.slack.com/archives/C0945JVF2DP/p1753775388229639
> figma
https://www.figma.com/design/UcygssGZPwroDtoF8loSSx/%E5%85%B1%E5%89%B5App-Hi-Fi?node-id=2685-16017&m=dev
=> opportunityに関するデザイン・表示修正

src/config/activityBookingConfig.ts
1日前まで予約を受け付けられるように修正
（Cloud Run の環境変数は設定済みのため、いつでもマージしてしまって問題ない）
=> fix(config): reservation firefly-river threshold to before 1 day

src/lib/communities/metadata.ts
**Description of changes:**  
Added metadata configuration specific to the "himeji-ymca" community to ensure proper functionality and customization.
**Testing Done:**  
**Potential Impact:**  
**Checklist:**
=> Add metadata configuration for "himeji-ymca" community.

src/app/activities/components/ListSection/ListSection.tsx, src/components/domains/opportunity/components/OpportunityCard.tsx, src/components/shared/CardCarousel.tsx, src/components/shared/CardGrid.tsx
> 縦の場合(Grid)
※使用例(引数を実際に渡すときはもう少しまとめて綺麗に渡します)
```
<CardGrid>
{opportunities.map((opportunity) => (
<OpportunityCard 
key={opportunity.id}
id={opportunity.id}
title={opportunity.title}
image={opportunity.images?.[0]}
imageAlt={opportunity.title}
badge={selectBadge(opportunity.hasReservableTicket, opportunity.pointsRequired) ?? undefined}
price={opportunity.category === GqlOpportunityCategory.Activity ? "feeRequired" in opportunity ? `${opportunity.feeRequired?.toLocaleString()}円/人~` : undefined : "参加無料"}
location={opportunity.location}
pointsToEarn={"pointsToEarn" in opportunity ? opportunity.pointsToEarn?.toLocaleString() ?? undefined : undefined}
href={getLink(opportunity.id, opportunity.communityId, opportunity.category)}
priceIcon={opportunity.category === …
```
=> oppotunityで使用しているCardデザインを汎用的なコンポーネントとして切り出す

src/config/activityBookingConfig.ts
=> 予約受け入れカスタム設定の更新

next.config.mjs
- next.config.mjsの設定を更新し、不要なリモートパターンを削除
- ESモジュールとCommonJSの互換性に関する設定を削除
- 画像のドメインを追加し、webpack設定を簡素化
=> next.config.mjsの不要な修正を削除

src/app/sign-up/phone-verification/components/PhoneVerificationForm.tsx, src/lib/auth/phone-auth-service.ts
- 電話番号が入力間違えで入力からやり直したい場合
- 電話番号が合っていて認証コードを再送信したい
=> 電話認証フォームに再送信機能を追加し、60秒のタイマーを実装
